export interface ProductItem {
  id: string
  name: string
  slug: string
  description: string
  price: number
  comparePrice?: number | null
  stock: number
  images: string
  sizes: string
  colors: string
  isVisible: boolean
  isFeatured: boolean
  categoryId: string
  category: { id: string; name: string; slug: string }
}

export const CATEGORIES_DATA = [
  { id: 'cat-mens-stitched', name: "Men's Stitched", slug: 'mens-stitched', image: 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=800&q=80' },
  { id: 'cat-mens-unstitched', name: "Men's Unstitched", slug: 'mens-unstitched', image: 'https://images.unsplash.com/photo-1605908502724-9060628a1dc5?w=800&q=80' },
  { id: 'cat-womens-stitched', name: "Women's Stitched", slug: 'womens-stitched', image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&q=80' },
  { id: 'cat-womens-unstitched', name: "Women's Unstitched", slug: 'womens-unstitched', image: 'https://images.unsplash.com/photo-1594938298596-70f56fb3cebc?w=800&q=80' },
  { id: 'cat-caps-headwear', name: 'Caps & Headwear', slug: 'caps-headwear', image: 'https://images.unsplash.com/photo-1521369909029-2afed882ba54?w=800&q=80' },
  { id: 'cat-western-wear', name: 'Western Wear', slug: 'western-wear', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80' },
]

export const ALL_PRODUCTS_CATALOG: ProductItem[] = [
  // ─── Men's Stitched ───
  {
    id: 'prod-ms-1',
    name: 'Classic White Shalwar Kameez',
    slug: 'classic-white-shalwar-kameez',
    description: 'A timeless classic white shalwar kameez crafted with premium spun cotton for everyday comfort and festive elegance.',
    price: 3500,
    comparePrice: 5000,
    categoryId: 'cat-mens-stitched',
    category: { id: 'cat-mens-stitched', name: "Men's Stitched", slug: 'mens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=800&q=80', 'https://images.unsplash.com/photo-1550614000-4b95d466f200?w=800&q=80']),
    sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
    colors: JSON.stringify([{ name: 'Crisp White', hex: '#FFFFFF' }]),
    stock: 4, // Low stock demo
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-ms-2',
    name: 'Charcoal Grey Kurta Set',
    slug: 'charcoal-grey-kurta-set',
    description: 'Sophisticated charcoal grey kurta with tailored slim trousers, finished with ban collar and mother-of-pearl buttons.',
    price: 4200,
    comparePrice: 6000,
    categoryId: 'cat-mens-stitched',
    category: { id: 'cat-mens-stitched', name: "Men's Stitched", slug: 'mens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80']),
    sizes: JSON.stringify(['M', 'L', 'XL']),
    colors: JSON.stringify([{ name: 'Charcoal', hex: '#36454F' }]),
    stock: 25,
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-ms-3',
    name: 'Embroidered Royal Waistcoat',
    slug: 'embroidered-waistcoat',
    description: 'Premium tailored waistcoat with subtle tone-on-tone embroidery, ideal for weddings and formal evening gatherings.',
    price: 5500,
    comparePrice: 7500,
    categoryId: 'cat-mens-stitched',
    category: { id: 'cat-mens-stitched', name: "Men's Stitched", slug: 'mens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?w=800&q=80']),
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    colors: JSON.stringify([{ name: 'Midnight Navy', hex: '#000080' }, { name: 'Jet Black', hex: '#000000' }]),
    stock: 18,
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-ms-4',
    name: 'Beige Cotton Blend Shalwar Kameez',
    slug: 'cotton-blend-shalwar-kameez',
    description: 'Comfortable breathable cotton-blend suit crafted for summer durability and effortless all-day wear.',
    price: 3800,
    comparePrice: 4800,
    categoryId: 'cat-mens-stitched',
    category: { id: 'cat-mens-stitched', name: "Men's Stitched", slug: 'mens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1605908502724-9060628a1dc5?w=800&q=80']),
    sizes: JSON.stringify(['M', 'L', 'XL']),
    colors: JSON.stringify([{ name: 'Warm Beige', hex: '#F5F5DC' }]),
    stock: 35,
    isVisible: true,
    isFeatured: false,
  },

  // ─── Men's Unstitched ───
  {
    id: 'prod-mu-1',
    name: 'Premium Wash & Wear Suit Fabric',
    slug: 'premium-wash-and-wear-suit',
    description: 'Wrinkle-resistant luxury wash and wear 4.5 meter unstitched suit fabric with a refined fall and soft drape.',
    price: 2800,
    comparePrice: 4000,
    categoryId: 'cat-mens-unstitched',
    category: { id: 'cat-mens-unstitched', name: "Men's Unstitched", slug: 'mens-unstitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80']),
    sizes: JSON.stringify(['4.5 Meters Unstitched']),
    colors: JSON.stringify([{ name: 'Deep Navy', hex: '#000080' }, { name: 'Coal Black', hex: '#111111' }]),
    stock: 6, // Low stock demo
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-mu-2',
    name: 'Egyptian Cotton Unstitched Fabric',
    slug: 'egyptian-cotton-unstitched',
    description: 'Superfine 100% Egyptian Giza cotton fabric with liquid ammonia finish, cool on skin during warm weather.',
    price: 3500,
    comparePrice: 5000,
    categoryId: 'cat-mens-unstitched',
    category: { id: 'cat-mens-unstitched', name: "Men's Unstitched", slug: 'mens-unstitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80']),
    sizes: JSON.stringify(['4.5 Meters Unstitched']),
    colors: JSON.stringify([{ name: 'Pure White', hex: '#FFFFFF' }, { name: 'Ivory Cream', hex: '#FFFDD0' }]),
    stock: 45,
    isVisible: true,
    isFeatured: false,
  },
  {
    id: 'prod-mu-3',
    name: 'Winter Karandi Heritage Suit',
    slug: 'winter-karandi-suit',
    description: 'Handloom-style textured Karandi winter fabric (4.5 meters) providing cozy warmth with rich rustic texture.',
    price: 3200,
    comparePrice: 4500,
    categoryId: 'cat-mens-unstitched',
    category: { id: 'cat-mens-unstitched', name: "Men's Unstitched", slug: 'mens-unstitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1616422285623-131696ee656b?w=800&q=80']),
    sizes: JSON.stringify(['4.5 Meters Unstitched']),
    colors: JSON.stringify([{ name: 'Mustard Gold', hex: '#DAA520' }, { name: 'Olive Green', hex: '#556B2F' }]),
    stock: 30,
    isVisible: true,
    isFeatured: false,
  },

  // ─── Women's Stitched ───
  {
    id: 'prod-ws-1',
    name: 'Chiffon Party Wear Embroidered Dress',
    slug: 'chiffon-party-wear-dress',
    description: 'Luxurious stitched chiffon 3-piece formal outfit embellished with intricate zari work and sequin accents.',
    price: 8500,
    comparePrice: 12000,
    categoryId: 'cat-womens-stitched',
    category: { id: 'cat-womens-stitched', name: "Women's Stitched", slug: 'womens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&q=80']),
    sizes: JSON.stringify(['S', 'M', 'L']),
    colors: JSON.stringify([{ name: 'Deep Maroon', hex: '#800000' }]),
    stock: 3, // Low stock demo
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-ws-2',
    name: 'Printed Summer Lawn Kurti',
    slug: 'printed-lawn-kurti',
    description: 'Vibrant digital printed lawn ready-to-wear shirt with tailored neckline and stylish sleeve borders.',
    price: 2200,
    comparePrice: 3200,
    categoryId: 'cat-womens-stitched',
    category: { id: 'cat-womens-stitched', name: "Women's Stitched", slug: 'womens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80']),
    sizes: JSON.stringify(['XS', 'S', 'M', 'L', 'XL']),
    colors: JSON.stringify([{ name: 'Azure Floral', hex: '#1E90FF' }]),
    stock: 40,
    isVisible: true,
    isFeatured: false,
  },
  {
    id: 'prod-ws-3',
    name: 'Emerald Silk Evening Tunic',
    slug: 'formal-silk-tunic',
    description: 'Raw silk tailored tunic featuring embroidered cuffs and gold threadwork on a relaxed silhouette.',
    price: 5400,
    comparePrice: 7800,
    categoryId: 'cat-womens-stitched',
    category: { id: 'cat-womens-stitched', name: "Women's Stitched", slug: 'womens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1550639525-c97d455acf70?w=800&q=80']),
    sizes: JSON.stringify(['M', 'L']),
    colors: JSON.stringify([{ name: 'Emerald', hex: '#50C878' }]),
    stock: 14,
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-ws-4',
    name: 'Lavender Cotton Co-ord Set',
    slug: 'cotton-coord-set',
    description: 'Chic matching two-piece top and trouser set tailored from breathable textured cotton.',
    price: 4800,
    comparePrice: 6500,
    categoryId: 'cat-womens-stitched',
    category: { id: 'cat-womens-stitched', name: "Women's Stitched", slug: 'womens-stitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=80']),
    sizes: JSON.stringify(['S', 'M', 'L']),
    colors: JSON.stringify([{ name: 'Lavender', hex: '#E6E6FA' }]),
    stock: 22,
    isVisible: true,
    isFeatured: false,
  },

  // ─── Women's Unstitched ───
  {
    id: 'prod-wu-1',
    name: '3-Piece Embroidered Lawn Suit',
    slug: '3-piece-embroidered-lawn',
    description: 'Unstitched 3-piece luxury lawn suit with embroidered neckline, printed trousers and chiffon dupatta.',
    price: 4500,
    comparePrice: 6500,
    categoryId: 'cat-womens-unstitched',
    category: { id: 'cat-womens-unstitched', name: "Women's Unstitched", slug: 'womens-unstitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1594938298596-70f56fb3cebc?w=800&q=80']),
    sizes: JSON.stringify(['3-Piece Unstitched']),
    colors: JSON.stringify([{ name: 'Blush Pink', hex: '#FFC0CB' }, { name: 'Mint Green', hex: '#98FF98' }]),
    stock: 5, // Low stock demo
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-wu-2',
    name: 'Khaddar Winter Unstitched Suit',
    slug: 'khaddar-winter-collection',
    description: 'Warm, cozy khaddar fabric 3-piece suit with woolen pashmina-blend printed shawl.',
    price: 3900,
    comparePrice: 5500,
    categoryId: 'cat-womens-unstitched',
    category: { id: 'cat-womens-unstitched', name: "Women's Unstitched", slug: 'womens-unstitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1622122201714-3677b10ffba5?w=800&q=80']),
    sizes: JSON.stringify(['3-Piece Unstitched']),
    colors: JSON.stringify([{ name: 'Rust Ochre', hex: '#B7410E' }]),
    stock: 35,
    isVisible: true,
    isFeatured: false,
  },
  {
    id: 'prod-wu-3',
    name: 'Festive Gold Chiffon 3-Piece',
    slug: 'festive-chiffon-suit',
    description: 'Heavily embroidered unstitched chiffon suit with hand-embellished patches and organza borders for wedding festivities.',
    price: 9500,
    comparePrice: 14000,
    categoryId: 'cat-womens-unstitched',
    category: { id: 'cat-womens-unstitched', name: "Women's Unstitched", slug: 'womens-unstitched' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80']),
    sizes: JSON.stringify(['3-Piece Unstitched']),
    colors: JSON.stringify([{ name: 'Antique Gold', hex: '#FFD700' }]),
    stock: 12,
    isVisible: true,
    isFeatured: true,
  },

  // ─── Caps & Headwear ───
  {
    id: 'prod-cap-1',
    name: 'Authentic Chitrali Wool Pakol',
    slug: 'authentic-wool-pakol',
    description: 'Traditional handcrafted woolen pakol from the northern valleys, warm and comfortable for everyday heritage wear.',
    price: 1200,
    comparePrice: 1800,
    categoryId: 'cat-caps-headwear',
    category: { id: 'cat-caps-headwear', name: 'Caps & Headwear', slug: 'caps-headwear' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=800&q=80']),
    sizes: JSON.stringify(['Standard Free Size']),
    colors: JSON.stringify([{ name: 'Earth Brown', hex: '#8B4513' }, { name: 'Heather Grey', hex: '#808080' }]),
    stock: 4, // Low stock demo
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-cap-2',
    name: 'Hand-knitted Cotton Prayer Cap',
    slug: 'hand-knitted-prayer-cap',
    description: 'Soft, breathable 100% white cotton crochet prayer topi with intricate geometric cutwork.',
    price: 450,
    comparePrice: 650,
    categoryId: 'cat-caps-headwear',
    category: { id: 'cat-caps-headwear', name: 'Caps & Headwear', slug: 'caps-headwear' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1521369909029-2afed882ba54?w=800&q=80']),
    sizes: JSON.stringify(['One Size']),
    colors: JSON.stringify([{ name: 'White', hex: '#FFFFFF' }]),
    stock: 120,
    isVisible: true,
    isFeatured: false,
  },
  {
    id: 'prod-cap-3',
    name: 'Premium Embroidered Velvet Kufi',
    slug: 'velvet-kufi',
    description: 'Structured royal black velvet kufi topi with golden wire embroidery on sides and crown.',
    price: 800,
    comparePrice: 1200,
    categoryId: 'cat-caps-headwear',
    category: { id: 'cat-caps-headwear', name: 'Caps & Headwear', slug: 'caps-headwear' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1534260933201-acfaee1dc3e5?w=800&q=80']),
    sizes: JSON.stringify(['S', 'M', 'L']),
    colors: JSON.stringify([{ name: 'Royal Black', hex: '#000000' }]),
    stock: 45,
    isVisible: true,
    isFeatured: false,
  },

  // ─── Western Wear ───
  {
    id: 'prod-ww-1',
    name: 'Heavyweight Cotton Crew Neck T-Shirt',
    slug: 'basic-crew-neck-tshirt',
    description: '220 GSM combed cotton crew neck tee with ribbed collar and relaxed drop-shoulder cut.',
    price: 1500,
    comparePrice: 2200,
    categoryId: 'cat-western-wear',
    category: { id: 'cat-western-wear', name: 'Western Wear', slug: 'western-wear' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80']),
    sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
    colors: JSON.stringify([{ name: 'Pure White', hex: '#FFFFFF' }, { name: 'Pitch Black', hex: '#000000' }]),
    stock: 80,
    isVisible: true,
    isFeatured: true,
  },
  {
    id: 'prod-ww-2',
    name: 'Slim Fit Indigo Stretch Jeans',
    slug: 'slim-fit-denim-jeans',
    description: 'Premium stretch indigo denim jeans with classic 5-pocket styling and antique brass rivets.',
    price: 3200,
    comparePrice: 4500,
    categoryId: 'cat-western-wear',
    category: { id: 'cat-western-wear', name: 'Western Wear', slug: 'western-wear' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80']),
    sizes: JSON.stringify(['30', '32', '34', '36']),
    colors: JSON.stringify([{ name: 'Indigo Blue', hex: '#0000FF' }]),
    stock: 50,
    isVisible: true,
    isFeatured: false,
  },
  {
    id: 'prod-ww-3',
    name: 'Matte Black Biker Jacket',
    slug: 'faux-leather-jacket',
    description: 'Modern structured faux leather jacket with metal zip closures and quilted shoulder panels.',
    price: 7500,
    comparePrice: 11000,
    categoryId: 'cat-western-wear',
    category: { id: 'cat-western-wear', name: 'Western Wear', slug: 'western-wear' },
    images: JSON.stringify(['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80']),
    sizes: JSON.stringify(['M', 'L', 'XL']),
    colors: JSON.stringify([{ name: 'Matte Black', hex: '#000000' }]),
    stock: 2, // Low stock demo
    isVisible: true,
    isFeatured: true,
  }
]
